# Generated by Django 3.1.5 on 2021-01-17 20:53

import classes.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
