# Generated by Django 3.1.5 on 2021-01-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210116_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='careers_interest',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Architecture and engineering'), (2, 'Arts, culture, and entertainment'), (3, 'Business, management, and administration'), (4, 'Communications'), (5, 'Community and social services'), (6, 'Education'), (7, 'Science and technology')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_time',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-3 hours'), (2, '4-6 hours'), (3, '6-8 hours'), (4, '10-12 hours')], default=1),
        ),
    ]
