# Generated by Django 3.1.5 on 2021-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Prefer not to say')], default=4),
        ),
    ]
