# Generated by Django 3.1.5 on 2021-01-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210116_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='careers_interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='challenging_courses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fields_help',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fields_interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sports_interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='study_time',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
