# Generated by Django 3.1.5 on 2021-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210117_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latest_course',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
