# Generated by Django 3.1.5 on 2021-01-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_latest_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latest_course',
        ),
    ]
