# Generated by Django 3.1.5 on 2021-01-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_latest_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latest_course',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
